import { build } from "esbuild";
import { mkdir, readFile, writeFile } from "node:fs/promises";

const handlers = ["installPilot", "dryRun", "testAlert", "checkEdmonton", "showStatus", "sendDailyReport", "stopPilot", "testWatchdogFailure"];
await mkdir(new URL("./dist/", import.meta.url), { recursive: true });
const result = await build({ entryPoints: [new URL("./src/apps-script.js", import.meta.url).pathname], bundle: true,
  format: "iife", globalName: "EdmontonMonitor", platform: "browser", target: "es2020", charset: "ascii",
  legalComments: "inline", minify: false, write: false });
const wrappers = handlers.map(name => `function ${name}() { return EdmontonMonitor.${name}(); }`).join("\n");
await writeFile(new URL("./dist/appsscript.json", import.meta.url), JSON.stringify({
  timeZone: "America/Edmonton", runtimeVersion: "V8", exceptionLogging: "STACKDRIVER",
  oauthScopes: ["https://www.googleapis.com/auth/script.external_request", "https://www.googleapis.com/auth/script.send_mail",
    "https://www.googleapis.com/auth/script.scriptapp", "https://www.googleapis.com/auth/spreadsheets"]
}, null, 2) + "\n");
const packages = ["htmlparser2", "entities", "domhandler", "domutils", "dom-serializer", "domelementtype", "url-parse", "querystringify", "requires-port"];
const { createRequire } = await import("node:module");
const { dirname, join } = await import("node:path");
const require = createRequire(import.meta.url);
const notices = [];
for (const name of packages) {
  let dir = dirname(require.resolve(name, { paths: [dirname(require.resolve("htmlparser2")), dirname(require.resolve("url-parse"))] }));
  for (let i = 0; i < 5; i += 1) {
    try {
      const pkg = JSON.parse(await readFile(join(dir, "package.json"), "utf8"));
      if (pkg.name === name) {
        let license;
        for (const file of ["LICENSE", "LICENSE.md", "LICENSE-MIT.txt"]) {
          try { license = await readFile(join(dir, file), "utf8"); break; } catch (_) { /* Try the package's next license filename. */ }
        }
        if (!license) throw new Error(`Missing license for ${name}`);
        notices.push(`${name} ${pkg.version}\n${license.replace(/\r\n/g, "\n").replace(/[ \t]+$/gm, "").trimEnd()}`);
        break;
      }
    } catch (error) { if (error.message.startsWith("Missing license")) throw error; }
    dir = dirname(dir);
  }
}
await writeFile(new URL("./dist/THIRD_PARTY_LICENSES.txt", import.meta.url), notices.join("\n\n") + "\n");
if (notices.length !== packages.length) throw new Error("Could not collect all dependency licenses.");
await writeFile(new URL("./dist/Code.gs", import.meta.url),
  `// Generated by build.mjs. Edit src/, then rebuild.\n/*\n${notices.join("\n\n").replaceAll("*/", "* /")}\n*/\n${result.outputFiles[0].text}\n${wrappers}\n`);
console.log("Built dist/Code.gs and the Apps Script manifest.");
